owner: envesko
repo: status

sites:
  - name: Envesko Launchpad - HTTPS
    url: https://envesko.com
  - name: Envesko Cloud - HTTPS
    url: https://envesko.cloud
  - name: Envesko Base - HTTPS
    url: https://base.envesko.com
    __dangerous__body_down: "Critical Error"
  - name: 201 (Shared - Web) - HTTPS
    url: $URL_201
  - name: 500 (Platform) - HTTPS
    url: $URL_500
  - name: srv2 (External) - HTTPS
    url: $URL_SRV2
  - name: 600 (Shared - Game) - API
    url: $URL_600
    expectedStatusCodes:
      - 401
  - name: 602 (Managed - Game) - API
    url: $URL_602
    expectedStatusCodes:
      - 401
  - name: 905 (Managed - Web) - HTTPS
    url: $URL_905

status-website:
  cname: status.envesko.com
  name: Envesko
  introTitle: "**Envesko** Status Monitor"
  introMessage: Incidents are tracked automatically by our system. If you encounter a problem with the platform, please [Open an Incident Report](https://github.com/envesko/status/issues/new/choose) or [Open a Ticket](https://base.envesko.com/contact.php).
  logoUrl: https://github.com/envesko/status/blob/master/assets/logo.png
  favicon: https://github.com/envesko/status/blob/master/assets/favicon.png
  navbar:
    - title: Status
      href: /
    - title: Open Incident
      href: https://github.com/$OWNER/$REPO/issues/new/choose
    - title: Open Ticket
      href: https://base.envesko.com/contact.php
    - title: Discord
      href: https://discord.gg/7zD8qBspuy
  assignees:
    - Brandin
  theme: night
  i18n:
    footer: Powered by [Envesko](https://envesko.com)